services:
  php:
    image: shinsenter/php:8.3-fpm-apache
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      DOCUMENT_ROOT: /public
      APP_GID: 1000
      APP_UID: 1000
      DEBUG: 1
  db:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
volumes:
  mysql_data:
